web-0 ansible_host=100.61.134.39
web-1 ansible_host=13.223.91.254
db-0  ansible_host=44.200.214.212
db-1  ansible_host=18.208.205.60


[web]
web-0
web-1

[web:vars]


[db]
db-0
db-1

[db:vars]


[all]
web-0
web-1
db-0
db-1

[all:vars]
ansible_ssh_user="ec2-user" 
ansible_ssh_private_key_file=/home/moustafa/remote_servers/ansible_private_key.pem
