apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-nginx
  name: my-nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
