apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-nginx
  name: my-nginx-svc-nodeport
spec:
  ports:
  - port: 81
    protocol: TCP
    targetPort: 80
  selector:
    app: my-nginx
  type: NodePort
status:
  loadBalancer: {}
